qa_fonacide/qa_fonacide/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from recepcion_xls.views import RedirectRegistrationView

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'qa_fonacide.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('recepcion_xls.urls',namespace='recepcion_xls',app_name='recepcion_xls')),
    url(r'^accounts/register/$', RedirectRegistrationView.as_view(), name='registration_register'),
    url(r'^accounts/', include('registration.backends.simple.urls'))
)

qa_fonacide/recepcion_xls/urls.py
from django.conf.urls import patterns, include, url

urlpatterns = patterns(
						'',
						url(r'^$','recepcion_xls.views.index',name='index'),
						url(r'^carga/$','recepcion_xls.views.carga',name='carga'),
						url(r'^descargar_modificado/(?P<nombre_archivo>\w+)/$','recepcion_xls.views.get_xls_modificado',name='descargar_modificado'),
						url(r'^descargar_xls/(\w+)/(\w+)/(\w+)/(\w+)/$','recepcion_xls.views.recrear_xls',name='recrear_xls'),
						url(r'^estado/$','recepcion_xls.views.estado_planillas',name='estado_planillas'),
						url(r'^dashboard/(\w+)/$','recepcion_xls.views.dashboard',name='dashboard'),
						url(r'^get_departamentos/$','recepcion_xls.views.get_departamentos',name='get_departamentos'),
						url(r'^get_distritos/$','recepcion_xls.views.get_distritos',name='get_distritos'),
						url(r'^descargar_zip/$','recepcion_xls.views.descargar_zip',name='descargar_zip'),
						#url(r'^descargar_xls/(?P<departamento>\w+)/(?P<distrito>\w+)/(?P<anho>\w+)/$','recepcion_xls.views.recrear_xls',name='recrear_xls'),
						url(r'^tareas/$','recepcion_xls.views.lista_tareas',name='lista_tareas'),
						url(r'^tareas/(?P<tarea_id>\d+)/$','recepcion_xls.views.realizar_tarea',name='realizar_tarea'),
						url(r'^asignar_tarea/(?P<tarea_id>\d+)/$','recepcion_xls.views.asignar_tarea',name='asignar_tarea'),
						url(r'^registro/$','recepcion_xls.views.register', name='register'),
					  	url(r'^login/$','recepcion_xls.views.user_login', name='login'),
					  	url(r'^logout/$','recepcion_xls.views.user_logout', name='logout')
					  )

qa_fonacide/recepcion_xls/forms.py
#coding: UTF-8
from django import forms
from django.contrib.auth.models import User
from captcha.fields import ReCaptchaField
from models import UploadFile, Tarea, Jurisdiccion, UserProfile
from registration.forms import RegistrationForm
from recepcion_xls import models

class UserReCaptchaForm(RegistrationForm):
	captcha = ReCaptchaField()
	

class UserProfileForm(forms.ModelForm):
	distrito = forms.ModelChoiceField(queryset=models.Jurisdiccion.objects.using("mec_public").filter(numero_nivel_jurisdiccion=3),
                                   required=False)
	class Meta:
		model = UserProfile
		fields = ('user','distrito',)

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class UploadFileForm(forms.ModelForm):
	class Meta:
		model = UploadFile
		fields = ('file',)

class CorreccionCodigosForm(forms.Form):
	codigo_institucion = forms.CharField(label='Código de Institución')
	codigo_local = forms.CharField(label='Código de Local')

qa_fonacide/recepcion_xls/views.py
#coding: UTF-8
import tempfile
import os
from StringIO import StringIO  
from zipfile import ZipFile  

from numbers import Number

from recaptcha.client import captcha 

from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, render_to_response, redirect
from django.template import RequestContext
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.core.files import File #Para manejo de archivo
from django.views.decorators.csrf import csrf_exempt



from forms import UserForm,UploadFileForm, CorreccionCodigosForm, UserReCaptchaForm

from models import UploadFile

from recepcion_xls import models

from recepcion_xls.validacion_forma import validar_forma, validadores

import constantes


from registration.backends.simple.views import RegistrationView

from datetime import date,datetime
from django.utils import timezone
from recepcion_xls.validacion_fondo import tareas
from recepcion_xls.validacion_fondo import validadores as validadores_fondo

from qa_fonacide.settings import BASE_DIR





# Create a new class that redirects the user to the index page, if successful at logging
class RedirectRegistrationView(RegistrationView):

	form_class = UserReCaptchaForm
	
	def get_success_url(self,request, user):
		return '/'



def register(request):

	# A boolean value for telling the template whether the registration was successful.
	# Set to False initially. Code changes value to True when registration succeeds.
	registered = False

	# If it's a HTTP POST, we're interested in processing form data.
	if request.method == 'POST':
		# Attempt to grab information from the raw form information.
		# Note that we make use of both UserForm and UserProfileForm.
		user_form = UserForm(data=request.POST)

		# If the two forms are valid...
		if user_form.is_valid():
			# Save the user's form data to the database.
			user = user_form.save()

			# Now we hash the password with the set_password method.
			# Once hashed, we can update the user object.
			user.set_password(user.password)
			user.save()

			# Update our variable to tell the template registration was successful.
			registered = True

		# Invalid form or forms - mistakes or something else?
		# Print problems to the terminal.
		# They'll also be shown to the user.
		else:
			print user_form.errors

	# Not a HTTP POST, so we render our form using two ModelForm instances.
	# These forms will be blank, ready for user input.
	else:
		user_form = UserForm()
	# Render the template depending on the context.
	return render(request,
			'recepcion_xls/register.html',
			{'user_form': user_form, 'registered': registered} )


def user_login(request):

	# If the request is a HTTP POST, try to pull out the relevant information.
	if request.method == 'POST':
		# Gather the username and password provided by the user.
		# This information is obtained from the login form.
		username = request.POST['username']
		password = request.POST['password']

		# Use Django's machinery to attempt to see if the username/password
		# combination is valid - a User object is returned if it is.
		user = authenticate(username=username, password=password)

		# If we have a User object, the details are correct.
		# If None (Python's way of representing the absence of a value), no user
		# with matching credentials was found.
		if user:
			# Is the account active? It could have been disabled.
			if user.is_active:
				# If the account is valid and active, we can log the user in.
				# We'll send the user back to the homepage.
				login(request, user)
				return HttpResponseRedirect('/')
			else:
				# An inactive account was used - no logging in!
				return HttpResponse("Su cuenta ha sido deshabilitada.")
		else:
			# Bad login details were provided. So we can't log the user in.
			print "Usuario y Contraseña invalidos: {0}, {1}".format(username, password)
			return HttpResponse("Invalid login details supplied.")

	# The request is not a HTTP POST, so display the login form.
	# This scenario would most likely be a HTTP GET.
	else:
		# No context variables to pass to the template system, hence the
		# blank dictionary object...
		return render(request, 'recepcion_xls/login.html', {})



# Use the login_required() decorator to ensure only those logged in can access the view.
@login_required
def user_logout(request):
	# Since we know the user is logged in, we can now just log them out.
	logout(request)
	# Take the user back to the homepage.
	return HttpResponseRedirect('/login/')


@login_required
def index(request):
	return render(request, 'recepcion_xls/index.html', {})


@login_required
def carga(request):

	if request.method == 'POST':
		form = UploadFileForm(request.POST, request.FILES)
	
		if form.is_valid():
			
			new_file = UploadFile(file = request.FILES['file'])
			anho = request.POST['anho']
			sobreescribir = request.POST['sobreescribir']
			print "Sobreescribir",sobreescribir
			#departamento_id = request.POST['departamento']
			#distrito_id = request.POST['distrito']
			anho = int(anho)
			
			print "Año: ",anho
			#print "Departamento ID: ",departamento_id
			#print "Distrito ID: ",distrito_id
			### get the inmemory file
			data = request.FILES.get('file') # get the file from the curl
			
			### write the data to a temp file
			tup = tempfile.mkstemp() # make a tmp file
			f = os.fdopen(tup[0], 'w') # open the tmp file for writing
			f.write(data.read()) # write the tmp file
			f.close()

			### return the path of the file
			filepath = tup[1] # get the filepath
			#Validar el archivo recibido
			if sobreescribir == "true":
				operacion = "sobreescribir"
			else:
				operacion = "normal"
			resultado_validacion_forma = validar_forma.validar(filepath,anho,operacion)
			
			#Prueba de concepto
			#resultado_validacion_forma = {	'valido':False, 
			#								'nroplanilla': 10,
			#								'nombreplanilla': "Sanitarios",
			#								'departamento': "Concepción",
			#								'distrito': 'Azotey',
			#								'log': True,
			#								'errores': "Listado\nDe\nErrores",
			#								'messages':[{'tags':"error",'text':"Planilla no procesada"}]}
			
			
				

			if resultado_validacion_forma['valido']: 
				resultado_validacion_forma["info"] = True
				#Guardar archivo Valido en carpeta correspondiente
				#obtener el departamento,distrito,fecha y tipo de planilla.
				planilla = resultado_validacion_forma["planilla"]
				departamento_obj = resultado_validacion_forma["departamento"]
				distrito_obj = resultado_validacion_forma["distrito"]
				filename = "Planilla"+planilla+"_"+distrito_obj.nombre_jurisdiccion+"_"+departamento_obj.nombre_jurisdiccion+".xls"
				#/planillas/Sanitarios/PlanillaSanitarios_distrito_departamento.xls
				models.set_file_path(planilla, filename)
				new_file.nro_planilla = resultado_validacion_forma["nroplanilla"]
				new_file.anho = anho
				new_file.departamento = departamento_obj.nombre_jurisdiccion
				new_file.distrito = distrito_obj.nombre_jurisdiccion
				new_file.departamento_id = departamento_obj.codigo_jurisdiccion
				new_file.distrito_id = distrito_obj.codigo_jurisdiccion
				new_file.save()
				resultado_validacion_forma['estado_planillas'] = get_estatus_planillas(departamento_obj,distrito_obj,anho)
			else:
				if resultado_validacion_forma["marcado"]:
				#Generar link para el archivo modificado
					nombre_archivo = os.path.basename(resultado_validacion_forma["marcado"])
					resultado_validacion_forma["marcado"] = nombre_archivo
					resultado_validacion_forma["info"] = True


					departamento_obj = resultado_validacion_forma["departamento"]
					distrito_obj = resultado_validacion_forma["distrito"]
					resultado_validacion_forma['estado_planillas'] = get_estatus_planillas(departamento_obj,distrito_obj,anho)
			

				else:
					resultado_validacion_forma["info"] = False
				#Los errores y mensajes ya estan cargados

			#Conseguir el estado de las otras planillas
			#Eliminacion del archivo temporal
			os.unlink(filepath)

			#retornar el html con la informacion sobre la planilla procesada
			#la misma incluye errores en caso de lo que los hubiese
			return render_to_response('recepcion_xls/carga_info.html',resultado_validacion_forma,context_instance=RequestContext(request))
			
			#return render(request,'recepcion_xls/index.html',{'form':form, 'errorlog':errorlog, 'log':log})
			#return HttpResponseRedirect(reverse('recepcion_xls:carga'))
	else:
		
		form = UploadFileForm()
	
	return render(request,'recepcion_xls/carga.html',{'form':form})



@login_required
def lista_tareas(request):
	usuario = request.user
	tareas_usuario = models.Tarea.objects.filter(usuario=usuario)
	
	tareas_disponibles = models.Tarea.objects.filter(estado="No asignada")
	
	#Chequeo de permisos para mostrar ciertas tareas
	

	#Traer tareas para las cuales tiene permiso
	#Filtrar aquellas que no pertenezcan al distrito


	

	return render(request,'recepcion_xls/tareas_asignadas.html',{"tareas_disponibles":tareas_disponibles,"tareas_usuario":tareas_usuario})

@login_required
def asignar_tarea(request,tarea_id):
	usuario = request.user
	tarea =models.Tarea.objects.filter(id_tarea=tarea_id)[0]
	tarea.estado = "Pendiente"
	tarea.usuario = usuario
	tarea.save()
	return HttpResponseRedirect(reverse('recepcion_xls:lista_tareas'))

@login_required
def realizar_tarea(request,tarea_id):
	"""
	Toma un id de tarea, y busca el presentador (vista)
	correspondiente para la misma. Este presentador tiene la 
	interfaz de resolucion de tareas
	"""
	tarea = models.Tarea.objects.filter(id_tarea=tarea_id)[0]
	if tarea.tipo == "Corrección de Códigos":
		return resolver_tarea_codigos(request,tarea_id)
	
	return HttpResponse("Tarea sin presentador")

@login_required
def resolver_tarea_codigos(request,tarea_id):
	#Conseguir la tarea
	tarea = models.Tarea.objects.filter(id_tarea=tarea_id)[0]
	#Que planilla?

qa_fonacide/templates/recepcion_xls/acerca.html
{% extends 'recepcion_xls/base.html' %}

{% load staticfiles %}

{% block title %} Recepción {% endblock %}

{% block css %}
        <link href="{% static 'css/dropzone.css' %}" type="text/css" rel="stylesheet"/>
{% endblock %}


{% block body_block %}

{% endblock %}

qa_fonacide/templates/recepcion_xls/carga_info.html
{% load static %}
{% static "" as baseUrl %}
{% for message in messages %}
    {% if 'success' in message.tags %}

        <div class="alert alert-success">
            <a class="close" href="#" data-dismiss="alert">×</a>
            <strong>Operación Exitosa: </strong>

                {{ message.text }}

        </div>
    {% endif %}
{% endfor %}

{% for message in messages %}
    {% if 'error' in message.tags %}
        <div class="alert alert-danger">
            <a class="close" href="#" data-dismiss="alert">×</a>
            <strong>Ha ocurrido un error: </strong>

                {{ message.text }}

        </div>
    {% endif %}
{% endfor %}

{% for message in messages %}
    {% if 'info' in message.tags %}
        <div class="alert alert-info">
            <a class="close" href="#" data-dismiss="alert">×</a>
            <strong>Información: </strong>

                {{ message.text }}

        </div>
    {% endif %}
{% endfor %}

{% for message in messages %}
    {% if 'warning' in message.tags %}
        <div class="alert alert-warning">
            <a class="close" href="#" data-dismiss="alert">×</a>
            <strong>Alerta: </strong>

                {{ message.text }}

        </div>
    {% endif %}
{% endfor %}

{% if info == True %}
<div class="panel panel-default">
  <div class="panel-heading"  role="tab" id="headingInfo">
  <h5 class="panel-title">
  <a data-toggle="collapse" data-parent="#accordion" href="#collapseInfo" aria-expanded="true" aria-controls="collapseInfo">
  Información
  </a>
  </h5>
  </div>
  
  <div id="collapseInfo" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingInfo">
    <div class="panel-body">
    
    <p><strong>Planilla:</strong> {{ nroplanilla }} - {{ planilla }} </p>
    <p><strong>Departamento:</strong> {{ departamento }} </p>
    <p><strong>Distrito:</strong> {{ distrito }} </p>

    
     <table class="table text-center">
      <thead >
        <tr>
          <th class="text-center">Planilla Nº 7 - Inmobiliario</th>
          <th class="text-center">Planilla Nº 9 - Aulas</th>
          <th class="text-center">Planilla Nº 10 - Sanitarios</th>
          <th class="text-center">Planilla Nº 11 - Otros</th>
          <th class="text-center">Planilla Nº 12 - Alimentación Escolar</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><img src="{{ baseUrl }}/images/{{ estado_planillas.0 }}" height="48" width="48"></td>
          <td><img src="{{ baseUrl }}/images/{{ estado_planillas.1 }}" height="48" width="48"></td>
          <td><img src="{{ baseUrl }}/images/{{ estado_planillas.2 }}" height="48" width="48"></td>
          <td><img src="{{ baseUrl }}/images/{{ estado_planillas.3 }}" height="48" width="48"></td>
          <td><img src="{{ baseUrl }}/images/{{ estado_planillas.4 }}" height="48" width="48"></td>
        </tr>
      </tbody>
    </table>



    {% if log == True %}
    <a class="btn btn-default pull-right" href="{% url 'recepcion_xls:descargar_modificado' marcado%}">Descargar Planilla con los errores marcados</a>
    {% endif %}
    </div>
  </div>
  </div>
{% endif %}

{% if log == True %}
<div class="panel panel-default">
  <div class="panel-heading"  role="tab" id="headingErr">
  <h5 class="panel-title">
  <a data-toggle="collapse" data-parent="#accordion" href="#collapseErr" aria-expanded="true" aria-controls="collapseErr">
  Errores
  </a>
  </h5>
  </div>
  
  <div id="collapseErr" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingErr">
    <div class="panel-body">


<textarea cols="120" rows="15" id="textoError">
  
{{ errores }}

</textarea>
<button class="btn btn-default pull-right" onclick="saveTextAsFile()">Guardar texto a archivo</button>


    </div>
  </div>
  </div>
{% endif %}

qa_fonacide/templates/recepcion_xls/estado_recepcion.html
{% extends 'recepcion_xls/base.html' %}

{% load staticfiles %}

{% block title %} Estado de Recepción de Planillas {% endblock %}

{% block css %}
 <link href="{% static 'css/fixed-header.css' %}" type="text/css" rel="stylesheet"/>
{% endblock %}

{% block side_block %}


<div class="panel panel-default">
  <div class="panel-heading"  role="tab" id="headingDown">
  <h5 class="panel-title">
  <a data-toggle="collapse" data-parent="#accordion" href="#collapseDown" aria-expanded="true" aria-controls="collapseDown">
  Descargas
  </a>
  </h5>
  </div>
  
  <div id="collapseDown" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingDown">
    <div class="panel-body">


<label> Departamento: </label>
<select id="departamento-id" class="form-control">
<option id="-1">Todos los departamentos</option>
</select>
<br>

<label> Distrito: </label>
<select id="distrito-id" class="form-control depdrop">
<option id="-1">Distrito</option>                
</select>
<br>


<button id="descargar" class="btn btn-default pull-right" onclick="descargar()">
Descargar compilado de planillas
</button>


</div>
  </div>
  </div>

<div class="panel panel-default">
  <div class="panel-heading"  role="tab" id="headingRef">
  <h5 class="panel-title">
  <a data-toggle="collapse" data-parent="#accordion" href="#collapseRef" aria-expanded="true" aria-controls="collapseRef">
  Referencias
  </a>
  </h5>
  </div>
  
  <div id="collapseRef" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingRef">
    <div class="panel-body">

<table class="table text-center table-condensed">
  <thead >
    <tr>
      <th class="text-center">Simbolo</th>
      <th class="text-center">Significado</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><img src="{% static 'images/mark.svg' %}" height="48" width="48"></td>
      <td>No se cargo aún.</td>
    </tr>
    <tr>
      <td><img src="{% static 'images/upload.svg' %}" height="48" width="48"></td>
      <td>Planilla cargada y con tareas pendientes.</td>
    </tr>
    <tr>
      <td><img src="{% static 'images/check.svg' %}" height="48" width="48"></td>
      <td>Planilla cargada y aceptada.</td>
    </tr>
  </tbody>
</table>

</div>
  </div>
  </div>

{% endblock %}

{% block body_block %}
<label>Año</label> <input type="text" id="datepicker" /> <button id="recargar" class="btn btn-default" onclick="cargar_estado()">
Actualizar
</button>
<div id="loader-estado"></div>
<div id="tablaEstados">
  
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'js/app.js' %}"></script>
<script src="{% static 'js/jquery.stickytableheaders.min.js' %}"></script>
<script src="{% static 'js/spin.min.js' %}"></script>
<link href="{% static 'css/dependent-dropdown.min.css' %}" media="all" rel="stylesheet" type="text/css" />
<script src="{% static 'js/dependent-dropdown.min.js' %}" type="text/javascript"></script>
<script>

function cargar_estado(){
    var anho = $('#datepicker').val()
    $('#tablaEstados').html("")
    console.log(anho)  
    $.ajax({
        url : "{% url 'recepcion_xls:dashboard' 'valor' %}".replace('valor',anho.trim()), // the endpoint
        type : "GET", // http method
        beforeSend: sLoadingEstadoPlanillas(),
        // handle a successful response
        success : function(response) {
          //console.log(response)
            $('#tablaEstados').html(response); // remove the value from the input
            var offset = $('.navbar').height();
            $("html:not(.legacy) table").stickyTableHeaders({fixedOffset: offset});
            //console.log("success"); // another sanity check
            fLoadingEstadoPlanillas();
        },

        // handle a non-successful response
        error : function(xhr,errmsg,err) {
            $('#tablaEstados').html("<div class='alert-box alert radius' data-alert>Oops! We have encountered an error: "+errmsg+
                " <a href='#' class='close'>&times;</a></div>"); // add the error to the dom
            console.log(xhr.status + ": " + xhr.responseText); // provide a bit more info about the error to the console
        }})    
}

var anho = $('#datepicker').val()
cargar_estado();

$('#datepicker').change(cargar_estado)

var options = [];
options.push('<option value="-1">Departamento</option>')
$.getJSON("{% url "recepcion_xls:get_departamentos" %}", function(result) {
for (var i = 0; i < result.lista_departamentos.length; i++) {
  options.push('<option value="',
  result.lista_departamentos[i][0], '">',
  result.lista_departamentos[i][1], '</option>');
}
options.push('<option value="-1">Todos los departamentos</option>')
$("#departamento-id").html(options.join(''));

});


//Para combo dependiente del primero
    $("#distrito-id").depdrop({
        url: '{% url "recepcion_xls:get_distritos" %}',
        depends: ['departamento-id'],
        placeholder: "Distrito",
        initialize:false,
        loading: false
      });

function descargar(){
  var anho = $('#datepicker').val()
  var valor1 = $('#departamento-id').val();
  var valor2 = $('#distrito-id').val();

  if(valor1 != -1 && valor2 != -1){
    valor2 = valor1+"-"+valor2
  }

  console.log("{% url 'recepcion_xls:descargar_zip' %}"+"?distrito_id="+valor2+"&departamento_id="+valor1+"&anho="+anho)
  window.location="{% url 'recepcion_xls:descargar_zip' %}"+"?distrito_id="+valor2+"&departamento_id="+valor1+"&anho="+anho
}

</script>

{% endblock %}

qa_fonacide/templates/recepcion_xls/login.html
{% extends 'recepcion_xls/base.html' %}

{% load staticfiles %}

{% block title %} Registro de Usuarios {% endblock %}

{% block body_block %}
        <h1>Login a QA FONACIDE</h1>

        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Usuario: <input type="text" name="username" value="" size="50" />
            <br />
            Contraseña: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="Ingresar" />
        </form>

{% endblock %}

qa_fonacide/templates/recepcion_xls/tareas_asignadas.html
{% extends 'recepcion_xls/base.html' %}

{% load staticfiles %}

{% block title %} Tareas Asignadas {% endblock %}

{% block side_block %}

<div class="panel panel-default">
  <div class="panel-heading"><h5>Explicación</h5></div>
  <div class="panel-body">
  <small><p class="text-justify">La sección tareas disponibles contiene las tareas de corrección no asignadas a ningun usuario. Si ud. desea resolver esa tarea haga click en el botón Añadir.</p>
  <p class="text-justify"> La sección tareas pendientes contiene las tareas de corrección asignadas a su usuario, las que un administrador le ha asignado o ud a añadido a sus pendientes. Para pasar a la pantalla de corrección y resolver la tarea haga click en el botón Resolver.</p>
  <p class="text-justify">En la sección tareas resueltas aparecerán las últimas 10 tareas resueltas por ud.</p></small>
  </div>
  </div>
{% endblock %}
{% block body_block %}
<div class="panel panel-default">
  <div class="panel-heading"><h4>Tareas Disponibles</h4></div>
  <div class="panel-body">
    <ul>
    {% for tarea in tareas_disponibles %}
    	{% if tarea.estado == "No asignada" %}
	        <li class="list-group-item list-group-item-info li-tarea">Planilla Nº {{ tarea.nro_planilla }} {{ tarea.tipo }}<a class="btn btn-info pull-right" href="{% url 'recepcion_xls:asignar_tarea' tarea.id_tarea %}">Añadir</a></li>
	    {% endif %}
    {% empty %}
        <li class="list-group-item list-group-item-info">No hay tareas disponibles.</li>
    {% endfor %}
    </ul>

  </div>
</div>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Tareas Pendientes</h4></div>
  <div class="panel-body">
    <ul>
    {% for tarea in tareas_usuario %}
    	{% if tarea.estado == "Pendiente" %}
	        <li class="list-group-item list-group-item-info li-tarea">Planilla Nº {{ tarea.nro_planilla }} {{ tarea.tipo }}<a class="btn btn-info pull-right" href="{% url 'recepcion_xls:realizar_tarea' tarea.id_tarea %}">Resolver</a></li>
	    {% endif %}
    {% empty %}
        <li class="list-group-item list-group-item-info">No tiene tareas asignadas.</li>
    {% endfor %}
    </ul>

  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Tareas Realizadas</h4></div>
  <div class="panel-body">
    <ul>
    {% for tarea in tareas_usuario %}
    	{% if tarea.estado == "Completa" %}
	        <li class="list-group-item list-group-item-info li-tarea">Planilla Nº {{ tarea.nro_planilla }} {{ tarea.tipo }}</li>
	    {% endif %}
    {% empty %}
        <li class="list-group-item list-group-item-info">No hay tareas resueltas por ud.</li>
    {% endfor %}
    </ul>

  </div>
</div>


{% endblock %}